services:
  backend:
    build: ./backend
    container_name: mean-backend
    ports:
      - "3000:8080"          # Host port 3000 maps to container port 8080
    environment:
      - MONGO_URL=mongodb://mongo:27017/meanapp
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mean-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mean-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

