# .github/workflows/docker-ci-cd.yml
name: Docker CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # -------------------------
    # 2. Log in to Docker Hub
    # -------------------------
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # -------------------------
    # 3. Build and push backend image
    # -------------------------
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: riyaz04k/crud-dd-task-mean-app-backend:latest

    # -------------------------
    # 4. Build Angular frontend
    # -------------------------
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Angular frontend
      working-directory: ./frontend
      run: npm run build -- --configuration production

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: riyaz04k/crud-dd-task-mean-app-frontend:latest

    # -------------------------
    # 5. Deploy to EC2 via SSH
    # -------------------------
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Clone the repo if it doesn't exist
          if [ ! -d "~/crud-dd-task-mean-app" ]; then
            git clone https://github.com/riyaz04k/crud-dd-task-mean-app.git ~/crud-dd-task-mean-app
          fi
          cd ~/crud-dd-task-mean-app
          git pull origin main
          docker compose pull
          docker compose up -d --build
